{"name": "Ошибка 404 Not Found при запросе на удаление курьера c несуществующим id.", "status": "passed", "description": "Отправлям DELETE запрос на ручку DELETE/api/v1/courier/:id c несуществующим id. Проверяем, что ответ 404 Not Found и сообщение в ответе \"Курьера с таким id нет\"", "steps": [{"name": "Генерация рандомного ID", "status": "passed", "start": 1739134608808, "stop": 1739134608808}, {"name": "DELETE request.", "status": "passed", "parameters": [{"name": "path", "value": "'/api/v1/courier/257922791'"}, {"name": "payload", "value": "{'id': '257922791'}"}], "start": 1739134608808, "stop": 1739134608855}], "start": 1739134608808, "stop": 1739134608856, "uuid": "ddb3cc2b-7bab-4384-8f6d-cf413aedc4a3", "historyId": "f07b12503581d22ddde1c52790437073", "testCaseId": "f07b12503581d22ddde1c52790437073", "fullName": "tests.test_delete_courier.TestDeleteCourier#test_delete_courier_id_not_exists_shows_error_404", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_delete_courier"}, {"name": "subSuite", "value": "TestDeleteCourier"}, {"name": "host", "value": "k-julls"}, {"name": "thread", "value": "10016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_delete_courier"}]}