{"name": "Ошибка 404 Not Found при запросе на принятие заказа c несуществующим ID заказа.", "status": "passed", "description": "Создаем курьера фикстурой courier_id и получаем его ID. Отправляется PUT запрос на ручку /api/v1/orders/accept/orderID?courierId=CourierID c несуществующим ID заказа. Проверяем, что код ответа 404 Not Found и текст ответа \"Заказа с таким id не существует\" Курьер удаляется из системы фикстурой courier_id.", "steps": [{"name": "Генерация рандомного ID", "status": "passed", "start": 1739134605494, "stop": 1739134605494}, {"name": "PUT request без payload", "status": "passed", "parameters": [{"name": "path", "value": "'/api/v1/orders/accept/508289009?courierId=471140'"}], "start": 1739134605494, "stop": 1739134605541}], "start": 1739134605493, "stop": 1739134605541, "uuid": "1d636d4b-43c3-4396-8374-1ecf7cc615c6", "historyId": "439c3fad956072105fea1d5fed35e9ab", "testCaseId": "439c3fad956072105fea1d5fed35e9ab", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_valid_courier_id_not_valid_order_id_shows_error_404", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "k-julls"}, {"name": "thread", "value": "10016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}