{"name": "Ошибка 404 Not Found при запросе на принятие заказа c несуществующим ID курьера.", "status": "passed", "description": "Создаем заказ фикстурой order_confirmed. Отправляется PUT запрос на ручку /api/v1/orders/accept/OrderID?courierId=CourierID c несуществующим ID курьера. Проверяем, что код ответа 404 Not Found и текст ответа \"Курьера с таким id не существует\"", "steps": [{"name": "Генерация рандомного ID", "status": "passed", "start": 1739134605299, "stop": 1739134605299}, {"name": "PUT request без payload", "status": "passed", "parameters": [{"name": "path", "value": "'/api/v1/orders/accept/972319?courierId=816126506'"}], "start": 1739134605299, "stop": 1739134605357}], "start": 1739134605298, "stop": 1739134605357, "uuid": "59de8070-331b-419f-806d-e9f14cc8da50", "historyId": "faa092fd401fb4cee5bf42ea537dc77c", "testCaseId": "faa092fd401fb4cee5bf42ea537dc77c", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_valid_order_id_not_valid_courier_id_shows_error_404", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "k-julls"}, {"name": "thread", "value": "10016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}